FROM nginxinc/nginx-unprivileged:1.27.3-alpine

LABEL maintainer="vladimir.gorej@smartbear.com" \
      org.opencontainers.image.authors="vladimir.gorej@smartbear.com" \
      org.opencontainers.image.url="https://editor-next.swagger.io" \
      org.opencontainers.image.source="https://github.com/swagger-api/swagger-editor/tree/next"

COPY ./build /usr/share/nginx/html

EXPOSE 8080

# start nginx
CMD ["nginx", "-g", "daemon off;"]
